name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix fmt -- --ci

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@master
      - name: minimum feature
        run: |
          cargo test --no-default-features
